# Generated by Django 3.0.7 on 2020-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itsp_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.TextField()),
                ('Team_ID', models.TextField()),
                ('Member_1', models.TextField()),
                ('Member_2', models.TextField()),
            ],
        ),
    ]
