# Generated by Django 3.0.7 on 2020-06-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsp_team',
            name='Team_name',
            field=models.CharField(max_length=100),
        ),
    ]
