# Generated by Django 3.0.7 on 2020-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0002_auto_20200623_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsp_team',
            name='Member_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itsp_team',
            name='Member_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itsp_team',
            name='Team_ID',
            field=models.CharField(max_length=100),
        ),
    ]
