# Generated by Django 3.0.7 on 2020-06-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0004_itsp_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itsp_team_name',
            old_name='Team_name',
            new_name='team_name',
        ),
    ]
