# Generated by Django 3.0.7 on 2020-06-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0005_auto_20200623_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itsp_team_name',
        ),
    ]
